name : Run tests
on : [push]

jobs:
  test:

    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install pip
        run: sudo apt-get -y install python3-pip & pip install --upgrade pip
      - name: Install environment
        run: pip install -i requirements.txt
      - name: Launch test
        run: pytest test/test_demo.py